# Form implementation generated from reading ui file 'Others\analytical-gui.ui'
# Created by: PyQt5 UI code generator 5.5.1
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Interface(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1122, 644)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 644))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem1, 4, 3, 3, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout.addItem(spacerItem3, 4, 0, 3, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(35, 25))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Company Logo/Images/logo.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(247, 31))
        self.label_4.setMaximumSize(QtCore.QSize(247, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.SearchText = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchText.setMinimumSize(QtCore.QSize(260, 31))
        self.SearchText.setMaximumSize(QtCore.QSize(1000, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SearchText.setFont(font)
        self.SearchText.setObjectName("SearchText")
        self.horizontalLayout.addWidget(self.SearchText)
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setMinimumSize(QtCore.QSize(107, 31))
        self.SearchButton.setMaximumSize(QtCore.QSize(107, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Button Icons/Images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton.setIcon(icon1)
        self.SearchButton.setIconSize(QtCore.QSize(20, 20))
        self.SearchButton.setObjectName("SearchButton")
        self.horizontalLayout.addWidget(self.SearchButton, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EndCalendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.EndCalendar.setMinimumSize(QtCore.QSize(259, 160))
        self.EndCalendar.setMaximumSize(QtCore.QSize(259, 160))
        self.EndCalendar.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.EndCalendar.setStyleSheet("selection-background-color: rgb(5, 147, 255);")
        self.EndCalendar.setSelectedDate(QtCore.QDate(2015, 12, 31))
        self.EndCalendar.setMinimumDate(QtCore.QDate(2014, 1, 1))
        self.EndCalendar.setGridVisible(True)
        self.EndCalendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.NoHorizontalHeader)
        self.EndCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.EndCalendar.setObjectName("EndCalendar")
        self.gridLayout_3.addWidget(self.EndCalendar, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(80, 25))
        self.label.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.WriteProgress = QtWidgets.QProgressBar(self.centralwidget)
        self.WriteProgress.setMinimumSize(QtCore.QSize(268, 23))
        self.WriteProgress.setMaximumSize(QtCore.QSize(16777215, 23))
        self.WriteProgress.setStyleSheet("")
        self.WriteProgress.setProperty("value", 0)
        self.WriteProgress.setTextVisible(False)
        self.WriteProgress.setFormat("")
        self.WriteProgress.setObjectName("WriteProgress")
        self.gridLayout_3.addWidget(self.WriteProgress, 19, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setMaximumSize(QtCore.QSize(67, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        spacerItem4 = QtWidgets.QSpacerItem(20, 16, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem4, 15, 2, 1, 1)
        self.StartCalendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.StartCalendar.setMinimumSize(QtCore.QSize(259, 160))
        self.StartCalendar.setMaximumSize(QtCore.QSize(259, 160))
        self.StartCalendar.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.StartCalendar.setStyleSheet("selection-background-color: rgb(5, 147, 255);")
        self.StartCalendar.setSelectedDate(QtCore.QDate(2015, 12, 1))
        self.StartCalendar.setMinimumDate(QtCore.QDate(2014, 1, 1))
        self.StartCalendar.setGridVisible(True)
        self.StartCalendar.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.StartCalendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.NoHorizontalHeader)
        self.StartCalendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.StartCalendar.setObjectName("StartCalendar")
        self.gridLayout_3.addWidget(self.StartCalendar, 1, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SiteList = QtWidgets.QTableWidget(self.centralwidget)
        self.SiteList.setMaximumSize(QtCore.QSize(16777215, 800))
        self.SiteList.setStyleSheet("")
        self.SiteList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SiteList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SiteList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SiteList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.SiteList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.SiteList.setTabKeyNavigation(False)
        self.SiteList.setAlternatingRowColors(True)
        self.SiteList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.SiteList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.SiteList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.SiteList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.SiteList.setObjectName("SiteList")
        self.SiteList.setColumnCount(3)
        self.SiteList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SiteList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SiteList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SiteList.setHorizontalHeaderItem(2, item)
        self.SiteList.horizontalHeader().setStretchLastSection(True)
        self.SiteList.verticalHeader().setVisible(False)
        self.SiteList.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_3.addWidget(self.SiteList, 0, 2, 15, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.InformationLabel = QtWidgets.QLabel(self.centralwidget)
        self.InformationLabel.setMaximumSize(QtCore.QSize(16777215, 21))
        self.InformationLabel.setInputMethodHints(QtCore.Qt.ImhNone)
        self.InformationLabel.setText("")
        self.InformationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InformationLabel.setObjectName("InformationLabel")
        self.horizontalLayout_3.addWidget(self.InformationLabel)
        self.AnimationLabel = QtWidgets.QLabel(self.centralwidget)
        self.AnimationLabel.setMinimumSize(QtCore.QSize(13, 13))
        self.AnimationLabel.setMaximumSize(QtCore.QSize(13, 13))
        self.AnimationLabel.setText("")
        self.AnimationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.AnimationLabel.setObjectName("AnimationLabel")
        self.horizontalLayout_3.addWidget(self.AnimationLabel)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 22, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem5, 6, 0, 1, 1)
        self.WriteButton = QtWidgets.QPushButton(self.centralwidget)
        self.WriteButton.setMinimumSize(QtCore.QSize(107, 31))
        self.WriteButton.setMaximumSize(QtCore.QSize(107, 31))
        self.WriteButton.setSizeIncrement(QtCore.QSize(30, 30))
        self.WriteButton.setBaseSize(QtCore.QSize(0, 0))
        self.WriteButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.WriteButton.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Button Icons/Images/write.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WriteButton.setIcon(icon2)
        self.WriteButton.setIconSize(QtCore.QSize(20, 20))
        self.WriteButton.setObjectName("WriteButton")
        self.gridLayout_3.addWidget(self.WriteButton, 7, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem6 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem6, 20, 0, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 0, 1, 16, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem8, 8, 0, 1, 1)
        self.SelectAll = QtWidgets.QCheckBox(self.centralwidget)
        self.SelectAll.setObjectName("SelectAll")
        self.gridLayout_3.addWidget(self.SelectAll, 9, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem9, 12, 0, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 4, 1, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.SearchText, self.SearchButton)
        MainWindow.setTabOrder(self.SearchButton, self.WriteButton)
        MainWindow.setTabOrder(self.WriteButton, self.SelectAll)
        MainWindow.setTabOrder(self.SelectAll, self.SiteList)
        MainWindow.setTabOrder(self.SiteList, self.StartCalendar)
        MainWindow.setTabOrder(self.StartCalendar, self.EndCalendar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analytical"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Powered</span> by <span style=\" color:#4885ed;\">G</span><span style=\" color:#db3236;\">o</span><span style=\" color:#f4c20d;\">o</span><span style=\" color:#4885ed;\">g</span><span style=\" color:#3cba54;\">l</span><span style=\" color:#db3236;\">e</span> Analytics</p></body></html>"))
        self.SearchButton.setText(_translate("MainWindow", "   Search"))
        self.label.setText(_translate("MainWindow", "Starting Date"))
        self.label_2.setText(_translate("MainWindow", "Ending Date"))
        item = self.SiteList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.SiteList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.SiteList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Website"))
        self.WriteButton.setText(_translate("MainWindow", "   Write"))
        self.SelectAll.setText(_translate("MainWindow", "Select All"))

import iconsRC
